/** Grok Bot / Cursor tool names → Sub8 tool names. MCP + catalog FALLBACK must equal this map. */
export const TOOL_ALIASES: Record<string, string> = {
  SendMessage: "send_message",
  SendToAgent: "message_teammate",
  CreateAgent: "create_teammate",
  CreateChannel: "create_channel",
  UpdateChannel: "update_channel",
  Task: "task",
  CheckSubagent: "check_subagent",
  MessageSubagent: "message_subagent",
  StopSubagent: "stop_subagent",
  CloudAgent: "cloud_agent",
  WebSearch: "web_search",
  WebFetch: "web_fetch",
  Screenshot: "computer",
  RequestBoxHelp: "request_box_help",
  Read: "read",
  AwaitShell: "await_shell",
  AskUser: "ask_user",
  Shell: "shell",
  UpdateState: "update_state",
  GetMcpTools: "get_mcp_tools",
  CallMcpTool: "call_mcp_tool",
  AuthenticateMcpServer: "authenticate_mcp_server",
  AddMcpServer: "add_mcp_server",
};
